version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    command: 'python3.10 bot_v01/__main__.py'
    volumes:
      - ./:/home/nftuser/src/app
    depends_on:
      - postgres
  api:
    build:
      context: .
      dockerfile: webapi.Dockerfile
    container_name: api_nft_explorer
    command: 'python3 -m uvicorn api.main:app --host 0.0.0.0'
    volumes:
      - ./:/home/nftuser/src/app
    ports:
      - "8000:8000"
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: worker_nft_explorer
    command: 'python3 -m celery -A api.celery_worker worker -l debug -Q main_queue -c 1'
    volumes:
      - ./:/home/workerr/src/app
    links:
      - api
    depends_on:
      - api
      - cache
  cache:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  postgres:
    image: library/postgres:14
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PORT=${PG_PORT}
    ports:
      - "5432:5432"
    volumes:
      - $HOME/PycharmProjects/Server/.db_data:/var/lib/postgresql/data


volumes:
  .db_data:
  cache:
    driver: local
