name: Deployment
on:
  push:
    branches: [ "develop" ]
jobs:
  job_one:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - name: test connect ssh connection
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.NNE_SECRET_KEY }}
          script: |
            ls -all
